# License server used by the "direct" edition (your own store).
# After installing "Dara License Server" on muhamedeid.com, copy the public key
# from Licenses → Settings into LICENSE_PUBKEY, then run: sh bin/package.sh
# (The public key is not a secret. It only verifies the server's signatures.)
LICENSE_API="https://muhamedeid.com/wp-json/dls/v1/"
LICENSE_PUBKEY="obermhEoTbeOifhP8lkLrBLzoFXkCwMDMfQ4dCPDWC0="
LICENSE_STORE="https://muhamedeid.com/"
